### ISSUE TITLE
[FEATURE] Create backups if backups are out of date

### ISSUE THREAD

**Issue by shinnova** [fosspill/FFXIV_Modding_Tool#123]
**Problem**
After a patch when one needs to update their index backups, the tool notifies you that your backups are out of date, but only prompts to ignore this fact.

**Solution**
It would be nice for the prompt to be if you want to backup your indexes right then and there.

**Comment by fosspill** [comment]
Closesd in https://github.com/fosspill/FFXIV_Modding_Tool/pull/124
