### ISSUE TITLE
[ISSUE] WARNING: Found a mod applied by an unknown application, only using FFMT

### ISSUE THREAD

**Issue by zeparu** [fosspill/FFXIV_Modding_Tool#202]
Im using an automated installer script [(zsh)](https://pastebin.com/JqHFubra), to automatically install a bunch of mods that i put in a folder

but sometimes it feels like specific files will trip up the program and it will report that the game has been modified by a different program

**Describe the bug**
-> install "problematic" mod
-> install another mod
```
WARNING: Found a mod applied by an unknown application, game stability cannot be guaranteed: 
Would you like to continue? (y/N)
```

**To Reproduce**
only certain mods will create this, but one file that consistently works for me is from https://github.com/skotlex/ffxiv-material-ui/releases/tag/3.2.0, in the OPTIONS archive, OPTIONS/04_GaugeBar/04_gaugebar-frame-silver/gaugebar-frame-silver.ttmp2

the ttmp2 probably has some metadata that FFMT is not handling correctly, pasting it into the XivMods.json, and then reading that information

**Expected behavior**
FFMT doesnt recognize itself as an unkown application

**Desktop (please complete the following information):**
 - OS: Linux, Manjaro
 - FFMT Version: ffmt 0.9.3.2, Game version 2020.8.1.0

**Comment by lillelilje** [comment]
```
{"TTMPVersion":"1.0s","Name":"gaugebar-frame-silver","Author":"skotlex","Version":"1.0.0","Description":null,"ModPackPages":null,"SimpleModsList":[{"Name":"Parameter_Gauge2","Category":"HUD","FullPath":"ui/uld/parameter_gauge2.tex","ModOffset":0,"ModSize":9984,"DatFile":"060000","ModPackEntry":null},{"Name":"parameter_gauge","Category":"UI","FullPath":"ui/uld/parameter_gauge.tex","ModOffset":9984,"ModSize":1177600,"DatFile":"060000","ModPackEntry":null},{"Name":"JobHudSimple_StackB","Category":"HUD","FullPath":"ui/uld/jobhudsimple_stackb.tex","ModOffset":1187584,"ModSize":2048,"DatFile":"060000","ModPackEntry":null},{"Name":"JobHudSimple_StackA","Category":"HUD","FullPath":"ui/uld/jobhudsimple_stacka.tex","ModOffset":1189632,"ModSize":2048,"DatFile":"060000","ModPackEntry":null}]}
```

**Comment by lillelilje** [comment]
Both @shinnova and I have been unable to reproduce the issue with the modpack you linked, but I have seen the issue before.

Since the "unknown application" is blank in your case it is safe to continue, though.

We'll go through the relevant parts of the code and see where it goes wrong

**Comment by lillelilje** [comment]
This seems to likely be a framework bug. I think the best solution would be to not throw a warning if the unknown application is blank.

**Comment by shinnova** [comment]
@zeparu 
Could you test with [this version](https://github.com/fosspill/FFXIV_Modding_Tool/files/5102982/FFXIV_Modding_Tool-linux-0.9.3.2-test.zip), and give me the output of the debug text of the previous import, if you get the unknown error again? Please reset your game before testing.

**Comment by zeparu** [comment]
```
Validating cache...
Checking backups before proceeding...
All backups present and up to date
Starting import...
Extracting data from gaugebar-frame-silver.ttmp2...
Data extraction successful.
Importing 4/4 mods from modpack...
DEBUG: Modpack name = gaugebar-frame-silver
DEBUG: Modpack author = skotlex
DEBUG: Modpack version = 1.0.0
DEBUG: Modpack url = 
DEBUG: Minimum framework version = 1.0.0.0
DEBUG: Source = FFXIV_Modding_Tool
Waiting for import process to respond...
If percentage doesn't display for a few minutes, wipe your mod_cache.db and try again
100%
4 mod(s) successfully imported.
Updated /home/zepar/.config/FFXIV_Modding_Tool/modlist.cgf to reflect changes.
Validating cache...
Checking backups before proceeding...
All backups present and up to date
WARNING: Found a mod applied by an unknown application, game stability cannot be guaranteed: 
Would you like to continue? (y/N)
y
Starting import...
Extracting data from round-background-job-icon.ttmp2...
Data extraction successful.
Importing 40/40 mods from modpack...
DEBUG: Modpack name = round-background-job-icon
DEBUG: Modpack author = skotlex
DEBUG: Modpack version = 1.0.1
DEBUG: Modpack url = 
DEBUG: Minimum framework version = 1.0.0.0
DEBUG: Source = FFXIV_Modding_Tool
Waiting for import process to respond...
If percentage doesn't display for a few minutes, wipe your mod_cache.db and try again
100%
40 mod(s) successfully imported.
Updated /home/zepar/.config/FFXIV_Modding_Tool/modlist.cgf to reflect changes.

```

**Comment by shinnova** [comment]
Thank you, that confirms the suspicion it is an issue in the framework. Our next release will ignore blank source names.
Out of curiosity, can you make this happen without the --noproblemcheck?

**Comment by zeparu** [comment]
yes, on normal release and the test version it still happens without skipping problemcheck
