### ISSUE TITLE
Testing needed: Version 0.9.5

### ISSUE THREAD

**Issue by lillelilje** [fosspill/FFXIV_Modding_Tool#212]
0.9.5 is a pretty big release with many changes and we'd love for people to help test and report issues.

**Comment by lillelilje** [comment]
@zeparu, sorry to contact you this way!

I remember you were using a script to install mods in the order you'd want.

The newest version supports installing multiple modpacks at once:
`ffmt mpi path/to/my/modpacks/*`

It would be fantastic if you could help test and provide feedback if there is anything else that would make it easier for you to use!

I had a peek at your script again and I think this should accomplish the exact same:

```
ffmt modpack import  <Path>/FFXIV\ Mods/*.ttmp2 <Path>/FFXIV\ Mods/late\ mods/* --all
```

**Comment by zeparu** [comment]
import seems to work, but it would be great if at the installing stage (after finishing all wizards), it would still say which mod its currently installing, i can only guess which one its doing right now based on the amount of mods in the modpack

**Comment by fosspill** [comment]
That's a very fair point and should be easy to add!

**Comment by lillelilje** [comment]
In the next version the message will look something like:
```
Data extraction successful.
Importing 2314/2314 mods from 000FULLPACK (Modpack 1/2)...
Waiting for import process to respond...
```

**Comment by taylor85345** [comment]
I've also tested out re-importing all of my modpacks using this feature, and it worked without a hitch. I've also been using a script until now and this is great.

I do wonder if it would be possible when importing multiple modpacks with the -a / -all flag, to also be able to use the -w flag to override individual modpacks that do require manual intervention. I have a couple of packs that I only use certain elements from, and it would be nice to not have to run a separate command for those.

**Comment by lillelilje** [comment]
Oh, I didn't even consider that possibility.
For now you can go without the --all and pick "import all" on the modpacks you would use --all on.

I wonder if this would be the cleanest syntax for importing mp2.ttmp2 with wizard and the rest without?
`ffmt mpi mp1.ttmp2 mp2.ttmp2 -w mp3.ttmp2 --all`

^ This one is problematic with how we parse stuff today and would make the logic a bit confusing in the end

or would this make more sense?
`ffmt mpi mp1.ttmp2 -w mp2.ttmp2  mp3.ttmp2 --all`

^ This one is doable with the current parsing, but I personally find it a bit confusing

or, just to be a bit creative:
`ffmt mpi mp1.ttmp2  w:mp2.ttmp2  mp3.ttmp2 --all`
The last one is obviously too creative in this case, but it'll take some work figuring out how this would make the most sense

@shinnova What's your take on this?

**Comment by taylor85345** [comment]
Keeping in mind that my "programming" knowledge is limited to the most rudimentary form of bash scripting, what I had envisioned would be something like:

`ffmt mpi mp1.ttmp2 -w mp2.ttmp2 mp3.ttmp2 -w mp4.ttmp2 mp5.ttmp2 --all`

Where in this example, mp2.ttmp2 and mp4.ttmp2 are specifying wizard import, while still honoring the originally specified order.

**Comment by lillelilje** [comment]
Yeah, that would indeed work but I do find it lacking when it comes to how intuitive it is.

I guess we could discuss more creative ideas. What about having a optional separate configuration file for each modpack where you could define all kinds of stuff? That may be very overkill though.

What about this idea @taylor85345: We make a separate command, say `ffmt modpack convert mp2.ttmp2` which would convert mp2.ttmp2 to a real "wizard modpack", which would force ffmt to show the wizard when you later import it, regardless of the --all flag?

A tiny bit of modpack info:
There are multiple types of modpacks, the ones you usually import are "Simple" modpacks.  There are a few distinct differences, but the main thing is that with a Wizard-type modpack `ffmt` has no choice but to show you the wizard.

**Comment by shinnova** [comment]
By making the -a and -w flags positional and take an optional argument, we could have it so that the user can override individual modpacks, but choose the global flag by defining it at the end of the command. I do agree with fosspill on how not intuitive that solution is though.

The conversion sounds like a good middle ground, with the added benefit of starting work on modpack editing functionality.

**Comment by lillelilje** [comment]
Truth be told, the convert command wouldn't really be more intuitive. Both the flag juggling and the new command options would have to be documented properly to be understood.

**Comment by taylor85345** [comment]
I'd say that converting modpacks could definitely work as a last ditch effort, and I'm all for modpack editing functionality, but this approach is probably better in the long run if we can figure out the syntax.

I do like your "creative" solution above from a readability standpoint, but I would worry about breaking tab-completion in some shells. I'm on fish, and tab-completion is a godsend for these long strings.

**Comment by lillelilje** [comment]
Yeah the w: solution isn't nice due to many things. 

Honestly I'm leaning towards saying that if you *need* wizard for a few specific modpacks it belongs in its own import order, and if you really want to ensure that wizard is always used the only clean way of doing it is converting it.

Another idea... Just thinking out loud: What about being able to do a dry-run of the "special" imports and have ffmt save which options you picked? this would make it prompt you if you want to use the remembered settings to override.
So, you later import the same modpack and you are asked if you want to import it the same way as last, including your mod choices?

I'll keep thinking though, and please shout if you think of a method or syntax that you really think works well! (Even if that's one I have expressed dislike for!)

**Comment by zeparu** [comment]
remembering import settings would be a huge plus, because right now im still spending like 5 minutes typing 1 or 2 and enter, and with it, my importing would be completely automatic

**Comment by lillelilje** [comment]
Would give us another unique feature over Textools too :^) 

What do you think @taylor85345? It seems that would resolve the most needs at once while remaining decently intuitive.

**Comment by taylor85345** [comment]
Yes, I also agree that the Dry Run options could be an excellent solution, combined with your idea above of separate configs per-modpack. Big full-wizard modpacks like the Hair Defined would be so much more manageable that way.

I think that per-modpack configs could also make post-import management a lot easier than the current method of hunting through the modlist.cfg file.

**Comment by lillelilje** [comment]
We already have a lot of work done on a better "post-import management" solution which lets you browse through and enable/disable what you want, or even use SQL queries to  directly modify the database to your liking.
It's being down prioritized to get Exports and Imports of textures and models in place though.

A per-modpack config would indeed work like a bit of a bandaid until a better solution is in place.
