### ISSUE TITLE
Having a hard time understanding the download steps?

### ISSUE THREAD

**Issue by meoowstics** [fosspill/FFXIV_Modding_Tool#221]
I'm not sure if this is the place to post this but this is the only place I could find to contact ^^; 

I'm trying to install ffmt for Mac and it says to download and extract the universal release and I can't at all find it. In general, reading everything as someone who's new to modding at all, it's all very daunting and I know this isn't directly related to the working of the app itself but is there any chance to have it so the download steps maybe come with images and the like for those of us who might be struggling?

**Comment by fosspill** [comment]
Thank you!
First, as a bit of information: we are working on a proper single-executable release, however, a bug (or flaw) in dotnet has proved that tricky so it's not our current focus.

Now, I see I forgot to change the wording properly. So, while I'm fixing that here is the general rundown:

1) Make sure dotnet core runtime is installed.
2) Download the right release version for you. As of writing that would be "FFXIV_Modding_Tool-mac-0.9.6.1.zip"
3) Unzip the file, I guess this happens automatically on Mac.
4) Open a terminal and `cd` into the ffmt folder (where the `ffmt` executable reside)
5) Run `ffmt setup` to set up your configuration file

**Comment by lillelilje** [comment]
Thank you!
First, as a bit of information: we are working on a proper single-executable release, however, a bug (or flaw) in dotnet has proved that tricky so it's not our current focus.

Regarding images: Until version 1.0 we'll rapidly change anything we feel needs changing so until then I will keep the guide as mostly text. 

Now, with that out of the way I've updated the guide to match how we name our releases currently:

![image](https://user-images.githubusercontent.com/1491401/94441821-8229b300-01a3-11eb-8721-de56b98b1551.png)

Does this make it clear enough, or are there certain steps that needs more clarification @meoowstics ?
 

Also, the guide is open source as well, so feel free to contribute if you have specific ideas for screenshots that would be helpful!

**Comment by lillelilje** [comment]
@meoowstics since you've been quiet for a while: if you want we could chat about this on a platform of your choice and I could guide you through the process. 
If not needed I'd love a reply to this issue.

**Comment by lillelilje** [comment]
We've made a early version of a release on homebrew, this may make it easier for novices to get started as well.

Feel free to give it a go:
1) Install homebrew (https://brew.sh has the command you need to run)
2) Run `brew install fosspill/ffmt/ffmt`
3) Run `ffmt setup`

**Comment by lillelilje** [comment]
Closing issue, but feel free to reopen it and I'll gladly work with you to make it work for you!

At 1.0 release we'll make sure to have a more detailed installation guide. Note that basic terminal knowledge will always be needed though.
