### ISSUE TITLE
[Feature+] Game launcher launcher

### ISSUE THREAD

**Issue by fosspill** [fosspill/FFXIV_Modding_Tool#24]
Should we include a game launcher launcher?

With this we could potentially launch the game and automagically disable mods when patch is detected, hence requiring no input from the user.

I also like the name game launcher launcher.

1. Could potentially scrape mogstation for patchnotes, or keep a list over update days in our repo which the script would check.
2. There might be other ways of getting this information. Someone has done work on a custom patcher for linux, so maybe there is a way to check which version is available for download.

**Comment by fosspill** [comment]
Example:

```$ ./ffxiv_textools_cli launch
Checking for current update version...
Current available version: 1.3.37
Installed version: 1.3.36
WARNING: Temporarily disabling all mods...
WARNING: Mods will be re-enabled after you quit the launcher
Starting launcher (with process.start)

Checking process status, repeatedly.
If process quits and game isn't running:
WARNING: New index files created.
WARNING: New backup triggered.
WARNING: All disabled mods have been enabled again.
~Goodbye~

```

**Comment by fosspill** [comment]
Seems like the most sensible way of doing this (without testing any further) is to make a proper "Launcher" which authenticates you and launches the game. However, if a new version is found it'll start the normal game launcher.

https://github.com/mclark4386/FF14Launcher/blob/1cd0dbd260f6ddbe6a3cb7ff95321f9bc90633b3/login.py

**Comment by fosspill** [comment]
Or - what about scraping the website for patch notes. That would require more logical thinking as they don't provide the game version, but it might be the easiest way.

**Comment by lillelilje** [comment]
Closing this for now.
Definitely out of scope.
