### ISSUE TITLE
mac : mods freeze my game

### ISSUE THREAD

**Issue by aeroplvne** [fosspill/FFXIV_Modding_Tool#265]
Hi, i'm trying to follow the steps to install FFMT Modding Tool on my mac, but when i arrived at the import one, it says that the command mpi is not found.

What did i do wrong ?
Thanks a lot

**Comment by lillelilje** [comment]
What does ./ffmt help show?

**Comment by vvsRin** [comment]
@aeroplvne are you importing a mod?

**Comment by aeroplvne** [comment]
@fosspill it says : zsh: permission denied: ./ffmt
@vvsRin i never used one but i'd like to try, that's why i'm trying to install everything (for the first time)

**Comment by vvsRin** [comment]
@aeroplvne is this a problem with installing the tool? or just using the mods?

**Comment by lillelilje** [comment]
Neither, I think

@aeroplvne you got to make sure you can execute the file. Mac may block that by default, so try to run `chmod +x ffmt`

**Comment by aeroplvne** [comment]
@fosspill @vvsRin okay everything is working ! i was putting the ">" in front of the text so it wasn't fully working ahah
but now i have an other issue ! so in ffmt everything seems to work perfectly, even the mod installation. But when i run the game, the screen turns black and freeze (i see the mouse, it just freeze before loading).
i tried to install the mod The Body 2.0 M. on my first installation, the game worked, i could log onto my character on ffxiv. it's when i removed the clothes (top) piece that it freeze (i assume it's cause it loads the mod, but doesn't fully work or something).

i tried many other things, like reseting the mod. didn't worked. i tried deleting him and installing Body 2.5 (this one, the game froze before even selecting a character).
i was on catalina mac when trying, so i updated it to have Big Sur, but doesn't seem to work either

**Comment by lillelilje** [comment]
I'm sadly unable to troubleshoot this issue as I do not have a mac license. 

Regardless, there is a pinned issue regarding this: https://github.com/fosspill/FFXIV_Modding_Tool/issues/237

There are multiple people that would very much appreciate help figuring that one out, but personally I don't know what else to do about this particular issue.

The main question for me would be: Can you run FFXIV through Wine, like we do on Linux? Would the same issue happen there?

Let's take this talk in the other issue, though.
