### ISSUE TITLE
[ISSUE] Blank line when installing modpack

### ISSUE THREAD

**Issue by lovelydumpling** [fosspill/FFXIV_Modding_Tool#269]
**Describe the bug**
When trying to install modpacks, I use the ./ffmt mpi (path) command and hit enter. It creates a new blank line where I can type, but nothing else is happening.
Example: 
![image](https://user-images.githubusercontent.com/30986053/142173305-540b83fc-84c1-4325-a88f-273e1e403fdd.png)

**To Reproduce**
1. Run command ./ffmt mpi path/to/modpack.ttmp2

**Expected behavior**
Start the installation wizard for choosing options to install in the modpack.

**Desktop (please complete the following information):**
 - OS: Linux (KDE Neon)
 - FFMT Version: 0.10

**Additional context**
I thought maybe it was due to the mod's file size, but trying smaller mods still produced this issue. Also I actually only just now realized this is a pre-release version, so I could try 0.9 and see if the problem persists. 

EDIT: This problem occurs in 0.9.10 as well. Worth noting this happens with the mpinfo command as well.

**Comment by lillelilje** [comment]
When you have spaces or special characters in a Linux terminal you'll most of the time have to escape them.

This means that your command should look something like:
`$ ffmt mpi /media/cindyao/LinuxHDD/work/Cin\'s\ Extra\ Special\ Mod\ Packs/The\ hrBody_1_5_1_Cut.ttmp2`

That happens automatically when you use tab to auto-complete the path, but you could also just put " around the path and it should also work:

`$ ffmt mpi "/media/cindyao/LinuxHDD/work/Cin's Extra Special Mod Packs/The hrBody_1_5_1_Cut.ttmp2"`

Feel free to reopen the issue if it happens again, or just keep chatting here if you need further assistance

**Comment by lovelydumpling** [comment]
That worked, thank you so much! As much of a linux newbie as I am, you'd think I'd have tried that because that's also how Windows works. Completely spaced on that one. Thank you for being patient with me :)
