### ISSUE TITLE
Lutris Steam version: Invalid game directory

### ISSUE THREAD

**Issue by Goelant** [fosspill/FFXIV_Modding_Tool#277]
**Solution here: https://github.com/fosspill/FFXIV_Modding_Tool/issues/277#issuecomment-1102928626**

**Describe the bug**
I'm trying to setup FFMT and i'm trying to change textures from a steam-downloaded FF14. As i'm setuping, I give where are my files but i'm getting the title's error, no matter what.
I tried to manually change the config file but it's not working, ffmt keeps saying that I didn't defined the gamedirectory as i'm trying to use it.

**To Reproduce**
1. Run command 'ffmt setup'
2. Set /home/<username>/Games/final-fantasy-xiv-online/drive_c/Program Files (x86)/Steam/steamapps/common/FINAL FANTASY XIV Online/ as a GameDirectory
3. See error 'WARNING: Invalid directory, please confirm that it matches the examples provided.'

**Expected behavior**
ffmt setup running fine and ffmt pc returning nothing (actually returning "ERROR: Invalid game directory")

**Desktop (please complete the following information):**
 - OS: Manjaro Linux with KDE Plasma
 - FFMT Version: 0.10.1.0 (Aur)

**Additional context**
Here is a little capture of the execution :
![image](https://user-images.githubusercontent.com/101263819/163889467-734a5128-f28f-4c4f-b5e1-b9af7388d0fe.png)

It may be coming from a verification done on the game files folder ? On steam it's called "FINAL FANTASY XIV Online" but it's mentionned "FINAL FANTASY XIV - A Realm Reborn" in the example

Thanks a lot for this tool and your work :D !

**Comment by lillelilje** [comment]
For now I'd just modify /home/xxxx/.config/FFXIV_Modding_Tool/config.cfg by hand!

What folders are in your FFXIV Online folder? could you show me?
Reason I'm asking is that validation is done within the folder to ensure it seems like a proper install

The specific code that fails is:
                 if(!_ValidDirectory(Path.Combine(_GameDirectoryFromConsole, "game", "sqpack", "ffxiv"), "GameDirectory")){


So, the path it's checking is:
/home/XXXX/Games/final-fantasy-xiv-online/drive_c/Program Files (x86)/Steam/steamapps/common/FINAL FANTASY XIV Online/game/sqpack/ffxiv
Within that folder we check for *.index files. if there are none it's not a valid directory.

Could you confirm that that folder has .index files in it?

**Comment by Goelant** [comment]
OH I'm so sorry I filled a bug for that : As I was searching for the .index file, I found the folder where I was trying to install ffmt didn't contain any game files :
![image](https://user-images.githubusercontent.com/101263819/164063309-6cfb09f7-c8b6-4954-9f08-d0433224b538.png)

As this is the __Lutris Steam version__ of FFXIV, used only to create a "steam link" to the Final Fantasy XIV [QuickLauncher](https://github.com/goatcorp/FFXIVQuickLauncher) (one of the ways to play FFXIV on Linux now that the old launcher is not working anymore and you've got a steam version of FFXIV) there isn't any game files here :'( !

I installed my game in another directory of my disk through [QuickLauncher](https://github.com/goatcorp/FFXIVQuickLauncher) download system ... 

I found the .index file in this other destination and ffmt config worked well :+1: 

I hope this issue can help other **lost Linux users** : **Look again if your FFXIV folder is the one containing game files ;)**

Thanks a lot for your reactivity :D

**Comment by lillelilje** [comment]
Hah, don't worry. I reworked that a little while ago so I thought I had broken it for a second! Happy you found the issue. I've added a link to your solution in the OP
