### ISSUE TITLE
[ISSUE] Seemingly incompatible with FFXIV 6.3

### ISSUE THREAD

**Issue by nixRidge** [fosspill/FFXIV_Modding_Tool#285]
**Describe the bug**
On Linux, I cannot make index backups or import modpacks anymore after updating to FFXIV 6.3
The tool worked fine on previous versions of the game.

I have tried reinstalling FFXIV as well as clearing all my FFMT config.

**To Reproduce**
1. Update to FFXIV 6.3
2. Run "ffmt b" to attempt and index backup

**Expected behavior**
Index files are backed up to my configured folder.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - FFMT Version: v0.10.1

**Additional context**
I've attached the error output to this issue.
[ffmt_ffxiv6.3_error.txt](https://github.com/fosspill/FFXIV_Modding_Tool/files/10452480/ffmt_ffxiv6.3_error.txt)
(The environment variable I use is needed because the app doesn't work on my Norwegian system otherwise.)

I understand the tool is on hiatus, and I usually do use Penumbra, however Penumbra is unable to load two very specific mods early enough, that is a texture swap for the title screen logo, and the other (arguably more important) swaps the Xbox buttons for a Nintendo Switch button layout (since I use a Switch Pro Controller). The latter crashes the game if attempted to be used with Penumbra, so I hope you don't mind me raising an issue for this as I still rely on ffmt.
Nevertheless, I'll understand if this sort of update doesn't happen. Thank you regardless!

**Comment by lillelilje** [comment]
@shinnova would you mind releasing a new version with the newest framework (w our patch)?

@FridgeRacer Its fun that this rather shabby tool may still have some small use so I’d love to have releases with the newest framework. 

When it comes to your first issue. I’ve used penumbra with title screen mods with no issues at all, so that’s rather strange. 

Let’s see what shinnova answers. Hopefully she’ll have time to look into this today

**Comment by nixRidge** [comment]
Thanks so much! FFMT makes my life a lot easier ☺️

> When it comes to your first issue. I’ve used penumbra with title screen mods with no issues at all, so that’s rather strange. 

Indeed, I believe it's very hit or miss, maybe on a computer to computer basis? Recently even TitleEdit (the Dalamud plugin) doesn't get loaded early enough; I guess at least, since none of my custom titles get loaded on boot, thus makes me think something is up in that regard. Overall not a gameplay impact of course, but hey, it's weird

**Comment by shinnova** [comment]
I haven't managed to get FFMT to compile successfully yet with the latest framework version, going to need a bit more time to figure out all the changes I need to make. I'm hoping I'll have a version to test tomorrow!

**Comment by shinnova** [comment]
I've managed to get it compiled now! @FridgeRacer could you test [ffmt_testing.tar.gz](https://github.com/fosspill/FFXIV_Modding_Tool/files/10483461/ffmt_testing.tar.gz) and tell me how it goes?

**Comment by nixRidge** [comment]
> I've managed to get it compiled now! @FridgeRacer could you test [ffmt_testing.tar.gz](https://github.com/fosspill/FFXIV_Modding_Tool/files/10483461/ffmt_testing.tar.gz) and tell me how it goes?

Of course! Just gave it a shot; after installing .NET Core 3.0.1, making a new config with FFMT's wizard and attempting to run the backup function, it gives me an SQLite related error: [ffmt_error_23jan2023.txt](https://github.com/fosspill/FFXIV_Modding_Tool/files/10483527/ffmt_error_23jan2023.txt)

Thanks so much for working on this by the way!

**Comment by shinnova** [comment]
That thankfully was an easy fix. It should work with this version! [ffmt_testing2.tar.gz](https://github.com/fosspill/FFXIV_Modding_Tool/files/10483628/ffmt_testing2.tar.gz)

**Comment by nixRidge** [comment]
The backup works now! But I'm getting the following error when trying to import a modpack. This occurs right after "Extracting data from [ttmp file]...":

One or more errors occurred. (Could not load file or assembly 'DotNetZip, Version=1.16.0.0, Culture=neutral, PublicKeyToken=6583c7c814667745'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))

I tried two just to make sure, if you need any of the .ttmp2 files, I can upload one no problem.

**Comment by lillelilje** [comment]
Thank you! New version coming later today I hope with all of those issues fixed

**Comment by shinnova** [comment]
I've done limited testing with this latest version, which has given me some errors, but I am unsure if these are caused by my outdated test setup or something else. Sadly I'm out of time for tonight, so please consider this a nightly version. 
[ffmt_testing3.tar.gz](https://github.com/fosspill/FFXIV_Modding_Tool/files/10494294/ffmt_testing3.tar.gz)

**Comment by nixRidge** [comment]
Worked like a charm, @shinnova! :D

**Comment by lillelilje** [comment]
> Worked like a charm, @shinnova! :D

That’s fantastic! Good job @shinnova 

I’ll close the ticket but we’ll see if the packaging scripts still work so we can put out a new, proper, release.
