### ISSUE TITLE
Better ProblemChecker output

### ISSUE THREAD

**Issue by fosspill** [fosspill/FFXIV_Modding_Tool#49]
The problemchecker output today is an overwhelming stream of useless information. It's like going to the doctor and receiving a 500 page report on every single bone in your body where the one broken one is mentioned on page 324 section 3 paragraph 5.

This really needs to be made cleaner. I'd gladly work on this, but I'd need some pointers about where to start (do I create a global array or a function in the problemchecker class that stores the issues and resolutions?)

Feature branch for better problem checker output is made.

I suggest something akin to this:

```

Checking for XXX problems..
44%...
Checkin for YYY problems ...
69%...
Checking for mod problems...
10%

The following problems were found and resolved:
oaisfoiahf oiahfioahfioh
GsdgS
DgSDGsdgsdg

ERROR: The following problems could not be resolved:
Broken toe. Please visit doctor.
```

**Comment by shinnova** [comment]
Creating an array in the problemchecker function sounds like the way to go, as you can make the individual checks return any issues found and add them to the array. If the array doesn't contain anything after the last check this means everything is okay, otherwise show what issues were found.
