### ISSUE TITLE
Shadowbringers support

### ISSUE THREAD

**Issue by fosspill** [fosspill/FFXIV_Modding_Tool#61]
This is an issue to track progress with shadowbringers support.

#59 Will contain the code needed
#60 Will contain website information

What issues are remaining to fix before these should be merged, @shinnova ?

**Comment by shinnova** [comment]
- [ ] TTMP.GetModPackJsonData is now an async task and needs to be awaited to get the data
- [ ] Progress<double> has been switched to IProgress, ReportProgress needs to be adjusted accordingly
- [ ] ProblemChecker functions are now async tasks and need to be awaited
- [ ] Dat functions are now async tasks and need to be awaited
