### ISSUE TITLE
Packaging for distros

### ISSUE THREAD

**Issue by fosspill** [fosspill/FFXIV_Modding_Tool#62]
Now we release both the bundled and unbundled versions of this tool, but it would be nice to have it released on various distros (at least have the packages available for one-click installs).

aur would be easy, but I do wonder if a .deb version would be nice too.

**Comment by fosspill** [comment]
Huh, this looks pretty sweet actually!

https://fpm.readthedocs.io/en/latest/use-cases/files.html

**Comment by lillelilje** [comment]
aur package available https://aur.archlinux.org/packages/ffmt-bin/ !

**Comment by Zyian** [comment]
It would probably be also handy to add this to Homebrew for macOS for easy installation. I can try to write one up this weekend since I have a Mac I can use.

https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by lillelilje** [comment]
That would be fantastic @Zyian!

**Comment by lillelilje** [comment]
So, I've looked a bit at it and it should be easy enough to be added to cask at least, if that allows to just use the precompiled and packed versions we have here already. If it requires building from source it'll be a bit more work of course, but the build.sh script shows the general idea at least :) 

If you try this and have any issues please poke me here and I'll provide as much assistance as I can!

**Comment by ashkitten** [comment]
trying to package this for nix, but i'm getting this error when running `ffmt pc`:
```
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/ash/.steam/root/steamapps/common/FINAL FANTASY XIV Online/game/\ffxivgame.ver'.
```
it seems like `Path.Combine` is using the wrong path separators for linux. is there something wrong with how i'm building it?

nix expressions here: https://gist.github.com/ashkitten/0af3ccde2c8d0fae5bf7f54b38eadaf3

edit: `ffmt v` works fine and outputs the correct version. it seems like `xivModdingFramework` has its own version check function, which inserts a backslash manually [here](https://github.com/TexTools/xivModdingFramework/blob/d792f128b1e10a72e77af6ead5329ddf103bd1ac/xivModdingFramework/General/GameInfo.cs#L70)... how does this work properly in the release binary?

**Comment by lillelilje** [comment]
Path.Combine is done correctly, but it seems we need to update the submodule as the commit isn't including our path fixes.

**Comment by lillelilje** [comment]
I've changed the xivmoddingframework submodule to track the correct commit.

The issue was that while we have already fixed the paths in the framework with a PR we did forget to update the submodule to track the fixed commit.

**Comment by ashkitten** [comment]
can you tag this change since v0.9.3.2 is broken when built from source?

**Comment by lillelilje** [comment]
Since that tag was broken I redid it with the proper fix and re-released. While not best practice it should get the job done in this case.

The next version will likely also be out today with some small fixes. That will of course be a new tag

**Comment by lillelilje** [comment]
FYI: After the next release (current Default branch) we should be completely compatible with Homebrew as no blobs will be in our repository.

My main concern is that this is a rather niche piece of software which would likely exclude anyone from submitting it to core, and I'm unfamiliar with cask's take on niche software.

Someone will likely have to maintain our own FFMT Tap here on github: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by lillelilje** [comment]
Anyone on Mac able to confirm if this works as expected?
https://github.com/fosspill/homebrew-ffmt

Basically: `brew install fosspill/ffmt/ffmt`

**Comment by Zyian** [comment]
Apologies for not getting around to this, I had forgotten.

I just tried out the brew install, works great on the first try (MacOS):
```
➜ brew install fosspill/ffmt/ffmt
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> New Formulae
libnetfilter-queue
==> Updated Formulae
Updated 14 formulae.
==> Updated Casks
brave-browser-beta                                                                         microsoft-edge-beta                                                                        prowritingaid                                                                              publii

==> Tapping fosspill/ffmt
Cloning into '/usr/local/Homebrew/Library/Taps/fosspill/homebrew-ffmt'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 89 (delta 41), reused 47 (delta 16), pack-reused 0
Unpacking objects: 100% (89/89), done.
Tapped 1 formula (114 files, 91.1KB).
==> Installing ffmt from fosspill/ffmt
==> Cloning https://github.com/fosspill/FFXIV_Modding_Tool.git
Cloning into '/Users/<user>/Library/Caches/Homebrew/ffmt--git'...
==> Checking out tag v0.9.6.1
HEAD is now at aecef7e Merge pull request #220 from fosspill/v0.9.6.1
Submodule 'xivModdingFramework' (https://github.com/TexTools/xivModdingFramework) registered for path 'xivModdingFramework'
Cloning into '/Users/<user>/Library/Caches/Homebrew/ffmt--git/xivModdingFramework'...
Submodule path 'xivModdingFramework': checked out 'aaf139879f626119bf8aa790e717c27d75968289'
/Users/<user>/Library/Caches/Homebrew/ffmt--git/xivModdingFramework
==> ./build.sh
🍺  /usr/local/Cellar/ffmt/0.9.6.1: 57 files, 31MB, built in 49 seconds

~ on 🐳 v19.03.12 () took 1m 15s
➜ ffmt --help
Config file saved to /Users/<user>/.config/FFXIV_Modding_Tool/config.cfg
Usage: ffmt [action] {arguments}

Available actions:
  modpack import, mpi      Import a modpack, requires a .ttmp(2) to be specified
  modpack info, mpinfo     Show info about a modpack, requires a .ttmp(2) to be specified
  mods enable, me          Enable all installed mods
  mods disable, md         Disable all installed mods
  mods refresh, mr         Enable/disable mods as specified in modlist.cfg
  backup, b                Backup clean index files for use in resetting the game
  reset, r                 Reset game to clean state
  problemcheck, pc         Check if there are any problems with the game, mod or backup files
  version, v               Display current application and game version
  help, h                  Display this text
  setup, s                 Run First-time Setup Wizard

Available arguments:
  -g, --gamedirectory      Full path to game install, including 'FINAL FANTASY XIV - A Realm Reborn'
  -c, --configdirectory    Full path to directory where FFXIV.cfg and character data is saved, including 'FINAL FANTASY XIV - A Realm Reborn'
  -b, --backupdirectory    Full path to directory with your index backups
  -t, --ttmp               Will be deprecated - Full path to .ttmp(2) file (modpack import/info only)
  -w, --wizard             Use the modpack wizard to select what mods to import (modpack import only)
  -a, --all                Import all mods in a modpack immediately (modpack import only)
  -npc, --noproblemcheck   Skip the problem check after importing a modpack
  -v, --version            Display current application and game version
  -h, --help               Display this text
  path/to/modpack.ttmp     Full path to modpack(s). Imports in the order given.

```

**Comment by lillelilje** [comment]
The PKGBUILD and .SPEC file (and more to come?) are now available at https://github.com/fosspill/FFMT-Packaging

**Comment by lillelilje** [comment]
Closing this issue as we now update homebrew, AUR and Opensuse. Other distros can use the prepackaged and/or selfextracting package.
