### ISSUE TITLE
[FEATURE] Use wizard selection logic for normal modpack imports

### ISSUE THREAD

**Issue by shinnova** [fosspill/FFXIV_Modding_Tool#68]
We should consider using the current wizard import logic for regular modpack imports when using the --custom flag instead of/as alternative to the config files that are in use currently.

**Describe the solution you'd like**
Allow picking what modifications to import when importing a modpack through the same selection method as the wizard import.

**Comment by fosspill** [comment]
The bad:
Scrollback lines.

The good:
Easier to maintain. Easier to use.


My suggestion would be to "fake" pages. Maybe with up to 50 on each:

```
> ffmt -t HUGE.ttmp --custom
Starting import...
Extracting data from testwizard.ttmp2...
Starting wizard...

Name: testwizard
Version: 1.0.0
Author: nova
This is to test multi options in a modpack wizard

The test group
Page: 1 out of 10
Choices:
    0 - Nr 1
        this is nr 1
    1 - Nr 2
        and number two
    2 - Nr 3
        dis be 3
Choose one or multiple (eg: 1 2 3, 0-3, *): 2

Page: 2 out of 10
Choices:
    0 - Nr 1
        this is nr 1
    1 - Nr 2
        and number two
    2 - Nr 3
        dis be 3
Choose one or multiple (eg: 1 2 3, 0-3, *): 2

```

**Comment by fosspill** [comment]
We should get rid of --custom all together and give a proper option when importing a simple modpack.

```
> ffmt -t HUGE.ttmp
Starting import...
Extracting data from testwizard.ttmp2...

Simple Modpack detected

Use Wizard?
(Y)es, let me select the mods.
(N)o, import everything.
```
