### ISSUE TITLE
[Feature] ModPack creation MVP

### ISSUE THREAD

**Issue by fosspill** [fosspill/FFXIV_Modding_Tool#8]
Support for modpack creation

**Comment by lillelilje** [comment]
@shinnova is working on this locally at the moment, but a new branch should soon™ be available with the new code for testing.

Will try to ping interested parties when that's the case.

**Comment by shinnova** [comment]
We now have the `modpack-creation` branch where, as of right now, ffmt is capable of creating a modpack out of your currently enabled mods.

@zeparu I've made a [quick build](https://github.com/fosspill/FFXIV_Modding_Tool/files/6535185/FFXIV_Modding_Tool-linux-creation-test.zip) with this functionality, would you be up for testing it?

**Comment by zeparu** [comment]
i created a modpack and reinstalled it now, but the installation of 719 mods went by suspiciously quick, i can test after the maintenance is down if everything went well

**Comment by zeparu** [comment]
worked for me

**Comment by shinnova** [comment]
Thank you so much for testing! 

> but the installation of 719 mods went by suspiciously quick

I believe the framework caches what mods you have imported for a short amount of time, so if you import those mods again soon after making the modpack the import should go faster than usual.

**Comment by shinnova** [comment]
@all-contributors please add @zeparu for User Testing

**Comment by lillelilje** [comment]
Included since 724f8d0358c543941cf9cebc06f168d8f8c818fc
