### ISSUE TITLE
[ISSUE] Found a mod applied by an unknown application

### ISSUE THREAD

**Issue by fosspill** [fosspill/FFXIV_Modding_Tool#89]
**Describe the bug**
The application sometimes complains about a mysterious mod applied by another application - even if that isn't the case.

**To Reproduce**
Unsure about steps to reproduce.
Presumably cancelling out at the wrong point in the import process?

**Expected behavior**
Importing a mod with FFMT should always conclude with FFMT recognizing it.

**Desktop (please complete the following information):**
 - OS: Linux and Mac
 - FFMT Version: v0.5 and v0.6 confirmed

**Additional context**
Might also be an issue with the reading of the mod information.

**Comment by fosspill** [comment]
This seems to have random chance of happening while importing a modpack. This is handled by the framework.


Theories so far:
- This is by design and we can ignore mods with no name from all checks
- This is a upstream bug that happens randomly (dependent on import order?)

Fixes/workarounds we can apply:
- Make sure problemchecker finds this issue
- Make sure unnamed mods are ignored from all checks

**Comment by shinnova** [comment]
After the newest version of the xivModdingFramework, it has become apparent that this is done by design, as the source is now set to "FilesAddedByTexTools". We can now safely ignore this.
